// export const BASE_URL = process.env.NODE_ENV === 'development' ? 'http://localhost:5000' : ''
export const BASE_URL = ''
export const LOADS_URL = '/api/loads'
export const ORDERS_URL = '/api/orders'
export const USERS_URL = '/api/users'
export const CARRIERS_URL = '/api/carriers'
export const ENTITIES_URL = '/api/entities'
